spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/cart
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql : true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8082